# Site settings
name: Sheng Wu
title: Student and Developer
email: pkernoobie@gmail.com
description: "Quick thoughts from a young person (that don't fit into 140 characters)"
baseurl: "http://sheng.io"
url: "http://sheng.io"
twitter: shenghis
github: shengwu

# Build settings
markdown: kramdown
permalinks: pretty
